apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client-deployment
    component: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client-deployment
      component: web
  template:
    metadata:
      labels:
        app: client-deployment
        component: web
    spec:
      containers:
        - name: client
          image: melanieammonite/k8s-client:latest
          ports:
            - containerPort: 3000
