apiVersion: atlas.mongodb.com/v1
kind: AtlasDatabaseUser
metadata:
  name: my-database-user
spec:
  roles:
    - roleName: "readWriteAnyDatabase"
      databaseName: "admin"
  projectRef:
    name: Deployment-test
  username: MONGO_USER
  passwordSecretRef:
    name: MONGO_PASSWORD
